const ATLAS = [
  {
    name: "Adult Brain",
    label: "ADULT BRAIN",
    className: "adult",
    img: require("@/assets/img/adult-brain.png"),
  },
  {
    name: "Fetal Brain",
    label: "FETAL BRAIN",
    className: "fetal",
    img: require("@/assets/img/fetal-brain.png"),
  },
  {
    name: "Tumour",
    label: "TUMOUR",
    className: "tumour",
    img: require("@/assets/img/tumour-brain.png"),
  },
  {
    name: "Organoid",
    label: "ORGANOID",
    className: "Organoid",
    img: require("@/assets/img/drganoid-brain.png"),
  },
  {
    name: "Mouse",
    label: "MOUSE BRAIN",
    className: "Mouse",
    img: require("@/assets/img/animal-brain.png"),
  },
];
export default ATLAS;
export const METHODS = [
  {
    label: "CellType",
    value: "CellType",
  },
  {
    label: "original_name",
    value: "original_name",
  },
  {
    label: "ACTINN",
    value: "ACTINN",
  },
  {
    label: "scARCH",
    value: "scARCH",
  },
  {
    label: "CHETAH",
    value: "CHETAH",
  },
  {
    label: "scmap",
    value: "scmap",
  },
  {
    label: "SingleCellNet",
    value: "SingleCellNet",
  },
  {
    label: "SingleR",
    value: "SingleR",
  },
  {
    label: "ScPred",
    value: "ScPred",
  },
];
export const REGION = [
  "Head",
  "Hypothalamus",
  "Cortical",
  "White matter",
  "Choroid",
  "Unclassified",
  "Midbrain",
  "Pluripotent stem cell",
  "Cerebral cortex",
  "Telencephalon",
  "Ganglionic eminences",
  "Thalamus",
  "Hippocampus",
  "Amygdala",
  "Diencephalon",
  "Cerebellum",
  "Presumptive cortex",
  "Basal ganglia",
  "Pons",
  "Hindbrain",
  "GE",
  "Pituitary gland",
  "cerebellar",
  "Grey matter",
  "Medulla",
  "Cortex",
  "Tumour",
  "Forebrain",
  "Brain",
];
export const CELLTYPE = [
  "Hippocampal CA1-3",
  "Ependymal",
  "Thalamic excitatory",
  "Hippocampal CA4",
  "Amygdala excitatory",
  "LAMP5-LHX6 and Chandelier",
  "Lower rhombic lip",
  "Medium spiny neuron",
  "MGE interneuron",
  "Bergmann glia",
  "Deep-layer intratelencephalic",
  "Oligodendrocyte",
  "Deep-layer near-projecting",
  "Fibroblast",
  "Upper-layer intratelencephalic",
  "Deep-layer corticothalamic and 6b",
  "Oligodendrocyte precursor",
  "unassigned",
  "CGE interneuron",
  "Mammillary body",
  "Astrocyte",
  "Upper rhombic lip",
  "Cerebellar inhibitory",
  "unannoted",
  "Eccentric medium spiny neuron",
  "Midbrain-derived inhibitory",
  "Committed oligodendrocyte precursor",
  "Vascular",
  "Miscellaneous",
  "Splatter",
  "Microglia",
  "Hippocampal dentate gyrus",
];
